
title: Welcome to Fika Social
description: Supporting businesses at all stages

#twitter: FikaSocial
#facebook: FikaSocial

telephone-number: (44) 117 950 25667
email-address: info@fikasocial.co.uk
address: Coming soon...

# location:
#  latitude: 51.4546372
#  longitude: -2.5926159

# Contact form tag line
contact-us: Have questions? We love to hear from customers, get in touch and we'll respond as quickly as possible


googleAnalytics: UA-45398981-1
domain: www.fikasocial.co.uk





# --------------------------------------------------------------------
#
#                  No editing below this line
#
# --------------------------------------------------------------------

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git']
gems:        []

timezone: GMT
encoding: UTF-8

permalink:     /blog/:year-:month-:day-:title.html
paginate_path: 'page:num'

markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
